vim.keymap.set("n", "<leader>i", function()
    vim.cmd("normal! mzgg=G`z")
end)

vim.keymap.set("n", "<leader>e", ":Ex<CR>")
vim.keymap.set("n", "<leader>p", '"+p')
vim.keymap.set("n", "<leader>c", '"+yy')
vim.keymap.set("v", "<leader>c", '"+y')
vim.keymap.set("n", "<leader>k", vim.lsp.buf.hover)
vim.keymap.set("n", "<leader>n", ":nohlsearch<CR>")
vim.keymap.set("n", "<leader>c", ":cd %:p:h<CR>")
vim.keymap.set("i", "<C-space>", "<C-x><C-o>")
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
vim.keymap.set("i", "<Tab>", "pumvisible() ? '<C-n>' : '<Tab>'", { noremap = true, expr = true })
vim.keymap.set("i", "<S-Tab>", "pumvisible() ? '<C-p>' : '<S-Tab>'", { noremap = true, expr = true })
vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "gd", vim.lsp.buf.definition, {buffer = true})
